// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run over the DIRECT connection (port 5432), not the pooled
    // pgbouncer URL — pgbouncer's transaction pooling breaks migrations.
    // The app runtime uses the pooled DATABASE_URL via the pg adapter (see db.ts).
    url: env("DIRECT_URL"),
  },
});
